# Generated by Django 5.0.4 on 2024-05-05 03:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("vacancies", "0002_remove_bookmark_user_id_bookmark_user"),
    ]

    operations = [
        migrations.AddField(
            model_name="vacancydetail",
            name="status",
            field=models.CharField(blank=True, default="active", max_length=25),
        ),
    ]
