# Generated by Django 5.0.4 on 2024-04-15 22:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("vacancies", "0003_alter_bookmark_user"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="bookmark",
            name="user",
        ),
        migrations.AddField(
            model_name="bookmark",
            name="user_id",
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="vacancy",
            name="url",
            field=models.URLField(unique=True),
        ),
    ]
