# Generated by Django 5.0.4 on 2024-05-06 09:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("vacancies", "0003_vacancydetail_status"),
    ]

    operations = [
        migrations.AlterField(
            model_name="vacancydetail",
            name="status",
            field=models.CharField(
                blank=True,
                choices=[("active", "Набор открыт"), ("closed", "Набор закрыт")],
                default="active",
                max_length=25,
            ),
        ),
        migrations.AlterField(
            model_name="vacancydetail",
            name="vacancy",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="details",
                to="vacancies.vacancy",
            ),
        ),
    ]
